codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 25%
    patch:
      default:
        target: auto
        threshold: 5%
        

comment:
  require_changes: true
