name: Release

on: push

jobs:

  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Update Libs
        run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
      - name: Build
        run: |
          shards build --production --release --static --no-debug
          strip ./bin/frightcrawler
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/frightcrawler
          token: ${{ secrets.RLS_TOKEN }}
