name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Update Libs
        run: apk add --update --upgrade --no-cache --force-overwrite libxml2-dev yaml-dev
      - name: Build
        run: |
          shards build --production --release --static --no-debug
          GET_VERSION=$(git describe --tags --abbrev=0)
          strip ./bin/frightcrawler
          mv ./bin/frightcrawler ./bin/frightcrawler-$GET_VERSION-linux-x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/frightcrawler-*
          token: ${{ secrets.RLS_TOKEN }}
